CREATE TABLE KAKAOBANK.REGIST (
  MEMBERNO INT(10) NOT NULL,
  MEMBERNAME VARCHAR(10) NULL,
  MEMBERBIRTHDAY VARCHAR(8) NULL,
  REGISTTIME DATETIME NOT NULL,
  CONSTRAINT REGIST_PK PRIMARY KEY(MEMBERNO)
);

CREATE TABLE KAKAOBANK.ACCOUNT (
  MEMBERNO INT(10) NOT NULL,
  ACCOUNTNO INT(13) NOT NULL,
  ZANGO INT(10) NOT NULL,
  DEALTIME DATETIME NULL,
  CONSTRAINT ACCOUNT_PK PRIMARY KEY(MEMBERNO, ACCOUNTNO)
);

CREATE TABLE KAKAOBANK.DEPOSIT (
  MEMBERNO INT(10) NOT NULL,
  ACCOUNTNO INT(13) NOT NULL,
  AMOUNT INT(10) NOT NULL,
  DEALTIME DATETIME NOT NULL,
  CONSTRAINT ACCOUNT_PK PRIMARY KEY(MEMBERNO, DEALTIME)
);

CREATE TABLE KAKAOBANK.WITHDRAW (
  MEMBERNO INT(10) NOT NULL,
  ACCOUNTNO INT(13) NOT NULL,
  AMOUNT INT(10) NOT NULL,
  DEALTIME DATETIME NOT NULL,
  CONSTRAINT ACCOUNT_PK PRIMARY KEY(MEMBERNO, DEALTIME)
);

CREATE TABLE KAKAOBANK.TRANSFER (
  MEMBERNO INT(10) NOT NULL,
  ACCOUNTNO INT(13) NOT NULL,
  TOBANK VARCHAR(10) NOT NULL,
  TOACCOUNTNO INT(12) NOT NULL,
  TOMEMBERNAME VARCHAR(10) NULL,
  AMOUNT INT(10) NOT NULL,
  DEALTIME DATETIME NOT NULL,
  CONSTRAINT ACCOUNT_PK PRIMARY KEY(MEMBERNO, DEALTIME)
);